# Generated by Django 2.2.10 on 2020-03-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook-f'), ('linkedin', 'fa-linkedin-in')], max_length=20),
        ),
    ]
